version: 2
jobs:
  build:
    steps:
      - checkout
      - run: docker login -e none@none.com -u ${DOCKER_USER} -p ${DOCKER_PASS} registry.uw.systems
      - run: docker build --rm=true -t registry.uw.systems/telecom/telecom-elasticsearch:latest .
      - run: docker tag registry.uw.systems/telecom/telecom-elasticsearch:latest registry.uw.systems/telecom/telecom-elasticsearch:$CIRCLE_SHA1
      - run: docker push registry.uw.systems/telecom/telecom-elasticsearch

workflows:
  version: 2
  build:
    jobs:
      - build:

